// Best-effort country-name -> ISO 3166-1 alpha-2 resolver for free-text
// location strings from feeds that don't supply a country code directly
// (USGS "place" strings, NASA EONET titles). Not exhaustive geocoding —
// just enough to attribute events to a country for the risk panel.
const COUNTRY_NAME_TO_ALPHA2: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  bangladesh: "BD",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  botswana: "BW",
  brazil: "BR",
  bulgaria: "BG",
  burundi: "BI",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  chad: "TD",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  czechia: "CZ",
  "czech republic": "CZ",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  denmark: "DK",
  djibouti: "DJ",
  "dominican republic": "DO",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  eritrea: "ER",
  estonia: "EE",
  eswatini: "SZ",
  ethiopia: "ET",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  gabon: "GA",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  greenland: "GL",
  guatemala: "GT",
  guinea: "GN",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kosovo: "XK",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  latvia: "LV",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  lithuania: "LT",
  luxembourg: "LU",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  mauritania: "MR",
  mauritius: "MU",
  mexico: "MX",
  moldova: "MD",
  mongolia: "MN",
  montenegro: "ME",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  burma: "MM",
  namibia: "NA",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  "north korea": "KP",
  "north macedonia": "MK",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  panama: "PA",
  "papua new guinea": "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  rwanda: "RW",
  "saudi arabia": "SA",
  senegal: "SN",
  serbia: "RS",
  "sierra leone": "SL",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  somalia: "SO",
  "south africa": "ZA",
  "south korea": "KR",
  "south sudan": "SS",
  spain: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  suriname: "SR",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  taiwan: "TW",
  tajikistan: "TJ",
  tanzania: "TZ",
  thailand: "TH",
  togo: "TG",
  "trinidad and tobago": "TT",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  turkmenistan: "TM",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "united states": "US",
  usa: "US",
  "u.s.": "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  venezuela: "VE",
  vietnam: "VN",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
  "puerto rico": "PR",
  "new caledonia": "NC",
  tonga: "TO",
  "solomon islands": "SB",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "republic of the congo": "CG",
  "cabo verde": "CV",
  "cape verde": "CV",

  // Demonyms/nationality adjectives — news headlines usually name the actor
  // this way ("Dutch central bank...", "Ukrainian officials...") rather
  // than the country noun itself. Ambiguous ones (e.g. bare "korean") are
  // deliberately omitted rather than guessing.
  dutch: "NL",
  british: "GB",
  russian: "RU",
  ukrainian: "UA",
  iranian: "IR",
  israeli: "IL",
  palestinian: "PS",
  chinese: "CN",
  taiwanese: "TW",
  american: "US",
  french: "FR",
  german: "DE",
  japanese: "JP",
  "south korean": "KR",
  "north korean": "KP",
  indian: "IN",
  pakistani: "PK",
  turkish: "TR",
  saudi: "SA",
  egyptian: "EG",
  syrian: "SY",
  iraqi: "IQ",
  lebanese: "LB",
  yemeni: "YE",
  afghan: "AF",
  emirati: "AE",
  qatari: "QA",
  polish: "PL",
  italian: "IT",
  spanish: "ES",
  brazilian: "BR",
  mexican: "MX",
  canadian: "CA",
  australian: "AU",
  indonesian: "ID",
  vietnamese: "VN",
  filipino: "PH",
  thai: "TH",
  nigerian: "NG",
  ethiopian: "ET",
  sudanese: "SD",
  somali: "SO",
  venezuelan: "VE",

  // Major conflict/politics-relevant cities — an article naming a city but
  // never the country by name (very common: "Kyiv", "Tehran", "Gaza")
  // otherwise fails to resolve at all.
  kyiv: "UA",
  kiev: "UA",
  moscow: "RU",
  tehran: "IR",
  "tel aviv": "IL",
  jerusalem: "IL",
  gaza: "PS",
  ramallah: "PS",
  beijing: "CN",
  taipei: "TW",
  pyongyang: "KP",
  seoul: "KR",
  damascus: "SY",
  baghdad: "IQ",
  kabul: "AF",
  islamabad: "PK",
  "new delhi": "IN",
  tokyo: "JP",
  london: "GB",
  washington: "US",
  paris: "FR",
  berlin: "DE",
  brussels: "BE",
  ankara: "TR",
  istanbul: "TR",
  riyadh: "SA",
  cairo: "EG",
  beirut: "LB",
  sanaa: "YE",
  khartoum: "SD",
  mogadishu: "SO",
  caracas: "VE",

  // Heads of state/government for countries this app tracks closely — a
  // headline naming the leader ("Putin warns NATO...") but not the country
  // or a demonym is common and otherwise resolves to nothing. Full
  // names/surnames only, never a bare first name or short token, so
  // there's no risk of matching as a substring inside an unrelated word
  // (see resolveCountryFromText below, which does a plain substring
  // search). This list drifts out of date as leadership changes — it's a
  // bonus signal, not load-bearing, since the demonym/country/city
  // matches above already cover the common case.
  "xi jinping": "CN",
  putin: "RU",
  zelensky: "UA",
  zelenskyy: "UA",
  netanyahu: "IL",
  "kim jong un": "KP",
  khamenei: "IR",
  pezeshkian: "IR",
  erdogan: "TR",
  "mohammed bin salman": "SA",
};

const NAMES_BY_LENGTH_DESC = Object.keys(COUNTRY_NAME_TO_ALPHA2).sort(
  (a, b) => b.length - a.length,
);

// Picks whichever recognized name appears EARLIEST in the text, not the
// longest one — a headline's subject/actor is almost always named first
// ("Dutch bank moves gold from UK to Canada" is a Netherlands story, not a
// UK or Canada one just because those names are longer or happen to match
// too). Length only breaks a tie between two names starting at the exact
// same position, which is when one is a genuine substring/qualifier of the
// other (e.g. "south korea" containing "korea") — the pre-sorted, longer
// name wins that comparison so the more specific match takes it.
export function resolveCountryFromText(text: string): string | null {
  const lower = text.toLowerCase();
  let best: { name: string; index: number } | null = null;
  for (const name of NAMES_BY_LENGTH_DESC) {
    const index = lower.indexOf(name);
    if (index === -1) continue;
    if (!best || index < best.index) {
      best = { name, index };
    }
  }
  return best ? COUNTRY_NAME_TO_ALPHA2[best.name] : null;
}
